### ISSUE TITLE
String 'True' treated as Int 

### ISSUE THREAD

**Issue by MartinBrugnara** [linsomniac/python-memcached#76] opened 2015-07-31 16:29 UTC
Context: memcached + python-memcached + django-memcached

Error: 
/usr/local/lib/python2.7/site-packages/memcache.py in _recv_value
1235            val = int(buf) 

Local vars:
```
buf	'True'
self	<memcache.Client object at 0x7f926d7590b8>
rlen	6
flags	2
server	<memcache._Host object at 0x7f926d826190>
```

This error does **not** occur **in v <= 1.54**

**Comment by linsomniac** [comment] 2015-07-31 17:36
Duplicate of #75

**Closed by linsomniac** 2015-07-31 17:36 UTC
